"""Canonical path for persisting intake_config.py from an Applicant."""

from __future__ import annotations

from dataclasses import asdict, fields
from datetime import datetime, timezone
from pathlib import Path

from formatting_utils import normalize_postal_code
from schema import Applicant

INTAKE_PATH = Path(__file__).parent / "intake_config.py"


def applicant_from_dict(data: dict) -> Applicant:
    """Build an Applicant from a flat dict (Streamlit session payload)."""
    valid = {f.name for f in fields(Applicant)}
    kwargs = {k: v for k, v in data.items() if k in valid}
    if kwargs.get("postal_code"):
        kwargs["postal_code"] = normalize_postal_code(kwargs["postal_code"])
    return Applicant(**kwargs)


def write_applicant(applicant: Applicant, source: str = "Ontario All-Quote Agent") -> Path:
    """Single canonical function to write gitignored intake_config.py."""
    lines = []
    for f in fields(Applicant):
        val = getattr(applicant, f.name)
        lines.append(f"        {f.name}={val!r},")

    body = "\n".join(lines)
    content = f'''"""
YOUR profile — generated by {source}.
This file is gitignored — do not remove it from .gitignore.
Update via Streamlit (app.py) or interactive_intake.py.
"""

from schema import Applicant


def build_applicant() -> Applicant:
    return Applicant(
{body}
    )
'''
    INTAKE_PATH.write_text(content, encoding="utf-8")
    return INTAKE_PATH


def write_intake_config(data: dict, source: str = "Ontario All-Quote Agent UI") -> Path:
    """Persist applicant fields from a dict (Streamlit path)."""
    return write_applicant(applicant_from_dict(data), source=source)


def load_existing_applicant() -> dict | None:
    """Load current intake if intake_config.py exists."""
    if not INTAKE_PATH.exists():
        return None
    try:
        from intake_config import build_applicant
        return asdict(build_applicant())
    except Exception:
        return None


def stamp_consent() -> str:
    return datetime.now(timezone.utc).isoformat()
