"""Write intake_config.py from structured applicant data."""

from datetime import date, datetime, timezone
from pathlib import Path

from formatting_utils import normalize_postal_code

INTAKE_PATH = Path(__file__).parent / "intake_config.py"


def write_intake_config(data: dict) -> Path:
    """Persist applicant fields to gitignored intake_config.py."""
    mode = data.get("mode", "estimate_only")
    consent = data.get("consent_timestamp") or ""

    content = f'''"""
YOUR profile — generated by the Ontario All-Quote Agent UI.
This file is gitignored — do not remove it from .gitignore.
Update via Streamlit (app.py) or interactive_intake.py.
"""

from schema import Applicant


def build_applicant() -> Applicant:
    return Applicant(
        mode={mode!r},
        consent_timestamp={consent!r},

        legal_name={data.get("legal_name", "")!r},
        date_of_birth={data.get("date_of_birth", "")!r},
        licence_number={data.get("licence_number", "")!r},
        licence_province="ON",
        licence_class={data.get("licence_class", "G")!r},
        date_first_licensed={data.get("date_first_licensed", "")!r},

        email={data.get("email", "")!r},
        phone={data.get("phone", "")!r},
        province={data.get("province", "Ontario")!r},

        street={data.get("street", "")!r},
        city={data.get("city", "")!r},
        postal_code={normalize_postal_code(data.get("postal_code", ""))!r},
        residence_start_date={data.get("residence_start_date", "")!r},

        vin={data.get("vin", "")!r},
        model_year={data.get("model_year", "")!r},
        make={data.get("make", "")!r},
        model={data.get("model", "")!r},
        ownership={data.get("ownership", "owned")!r},
        annual_km={data.get("annual_km", "")!r},
        commute_km_one_way={data.get("commute_km_one_way", "")!r},
        primary_use={data.get("primary_use", "commute")!r},

        current_insurer={data.get("current_insurer", "")!r},
        years_continuously_insured={data.get("years_continuously_insured", "")!r},
        accidents_last_6y={data.get("accidents_last_6y", "none")!r},
        convictions_last_3y={data.get("convictions_last_3y", "none")!r},

        effective_date={data.get("effective_date") or date.today().isoformat()!r},
        liability_limit={data.get("liability_limit", "2000000")!r},
        dcpd_included={data.get("dcpd_included", True)!r},
        collision_deductible={data.get("collision_deductible", "1000")!r},
        comprehensive_deductible={data.get("comprehensive_deductible", "1000")!r},
        opcf_44r={data.get("opcf_44r", True)!r},
        telematics_opt_in={data.get("telematics_opt_in", False)!r},
    )
'''
    INTAKE_PATH.write_text(content, encoding="utf-8")
    return INTAKE_PATH


def load_existing_applicant() -> dict | None:
    """Load current intake if intake_config.py exists."""
    if not INTAKE_PATH.exists():
        return None
    try:
        from intake_config import build_applicant
        from dataclasses import asdict
        return asdict(build_applicant())
    except Exception:
        return None


def stamp_consent() -> str:
    return datetime.now(timezone.utc).isoformat()
